<template>
  <div class="new1">
    <img alt="coronavirus" src="../assets/copas.jpg" />
    <main class="container">
      <h2>¿Partidos de Copa a puertas cerradas por coronavirus?</h2>
        <h4>Los equipos argentinos que juegan esta semana por la Libertadores están expectantes en caso de alguna decisión del Gobierno nacional. Por ahora se juega con gente, pero no descartan que se modifique. Habló el Ministro de Salud de la Ciudad. ¿Qué dijo? ¿Y la postura de Conmebol?</h4>
          <p>En Italia varios partidos se juegan a puertas cerradas. En Francia se postergó un partido por una amenaza de coronavirus. En Inglaterra se evita el saludo entre los jugadores y los árbitros antes del comienzo de los encuentros. Y en Estados Unidos bajaron el Master 1000 de Indian Wells y la NBA advirtió sobre la posibilidad de jugar partidos sin gente. En Argentina, por lo pronto, el Ministro de Salud de la Ciudad, Fernán Quirós, anunció este lunes la suspensión de distintos espectáculos internacionales. ¿Y el fútbol? ¿Y los encuentros de esta semana de la Copa Libertadores?</p>
          <p>El primer partido de esta semana será este martes, cuando Boca reciba a Deportivo Independiente Medellín en la Bombonera, con entradas agotadas. El miércoles será el turno de River frente a Binacional de Perú en el Monumental, aunque por la sanción de Conmebol ya jugará a puertas cerradas. Y el jueves le tocará a Racing​ enfrentar en el Cilindro a Alianza Lima de Perú. En tanto, a Tigre y Defensa y Justicia les toca presentarse de visitante.</p>
          <p>Con tanta aglomeración de público, la pregunta resultó inevitable y los rumores empezaron a circular desde bien temprano. En una entrevista en radio La Red, se lo preguntaron al presidente de Boca, Jorge Amor Ameal. "Se hablará. Si es necesario jugar a puertas cerradas por la salud de la gente, lo vamos a hacer", dijo el dirigente. Y agregó: "Hay que bajar el temor, la gente no tiene que vivir con temor, hay que tomar todas las precauciones necesarias".</p> 
          <p>La Conmebol, mientras tanto, avisó que no tomará decisiones por cuenta propia, sino que estará alerta a lo que suceda en cada país y decidan los gobiernos locales. Según el protocolo, "ante la excepcionalidad de la situación en torno a la evolución del Coronavirus, y acorde a las recomendaciones de las autoridades internacionales en salud pública, CONMEBOL analizará detalladamente cada posible riesgo y estudiará cómo afecta a sus competiciones".</p>
          <p>Y agregó: "La Confederación consensuará con gobiernos nacionales y locales, así como con las Asociaciones miembro y los clubes participantes en sus torneos las medidas pertinentes para preservar la salud de deportistas, hinchadas y la gran familia del fútbol continental"</p> 
          <p>Por su parte, el Gobierno de la Ciudad espera indicaciones de Nación, cuya última "recomendación" fue no realizar eventos con público internacional. "Como medida de hoy, en términos de espectáculos de mucha participación, la única medida que hemos tomado y que compartimos con la Nación es que aquellos espectáculos que esencialmente se organicen con gente del extranjero, como encuentros internacionales que traigan mucha gente de Europa y del otros lugares del mundo, son los que al día de hoy no vamos a permitir realizar", dijo Quirós en una conferencia de prensa.</p>         
          <p>Sin embargo, cuando al Ministro de Salud le preguntaron directamente por los partidos de la Copa Libertadores, explicó: "No hay ningún espectáculo deportivo que tenga hinchada visitante con presencia de europeos, no hay necesidad de hacer lo que decís vos (jugar sin gente)". Y completó: "No hay necesidad de tomar otra decisión porque en Argentina al día de hoy no está circulando el virus".</p>
          <p>A pesar de esa afirmación, la situación en algún momento puede cambiar en caso de una nueva directiva del Gobierno nacional, según le explicaron a Olé. Y si bien el partido de este martes de Boca parece estar a salvo, todos los clubes están atentos...</p>
          <p>El DIM de Colombia, por lo pronto, llegó al aeropuerto de Ezeiza por la madrugada y a varios jugadores se los vio con barbijos, protegiéndose de cualquier posibilidad de contagio.</p>
    </main>
  </div>    
</template>

