<template>
  <div class="new4">
    <img alt="quiebra" src="../assets/mufa.jpg">
    <main class="container">
      <h2>El día que la gente de Racing conmovió al mundo</h2>
        <h4>Este 7 de marzo se cumplen 21 años de la fecha en que los hinchas, pese a que Racing no jugaba, coparon el Cilindro para oponerse al cierre del club. Un hecho memorable.</h4>
          <p>Cada 7 de marzo, desde hace 21 años, a los hinchas de Racing los acomete el recuerdo de aquella angustia que les revolvía el estómago y de una resistencia memorable. Una demostración de amor por un club nunca antes vista, acaso, en el mundo entero. Un día como hoy, pero con el almanaque de 1999, la gente de la Academia copó el Cilindro a pesar de que el equipo no podía jugar. Y no sólo eso: lograron una mayor convocatoria que los estadios donde sí hubo fútbol...</p>
          <p>Racing no jugó en aquella tarde por una orden judicial . En realidad, no pudo hacerlo contra Talleres, en la primera fecha del torneo. Se desangraba. Agonizaba. Los fanas debían actuar. Justo ellos, los reyes del aliento, no se iban a quedar de brazos cruzados. Tenían algo que decir, algo que transmitir desde las tribunas. Muchos, también, desde el césped.</p>
          <p>Acostumbrados al sufrimiento de épocas de nefastas administraciones dirigenciales, nunca habían bajado a semejante profundidad de padecimientos. Ellos fueron al Presidente Perón con el corazón en una mano y el alma en la otra. Apretados por el dolor y, al mismo tiempo, con esas fuerzas que surgen en situaciones límites. Lo suficiente como para que pudieran elevar su voz en el tono más alto y conmovedor que jamás se les haya escuchado.</p> 
          <p>Gritaban bien fuerte. Desesperados. Con rostros desencajados. Y ese pedido se hizo súplica. Historia pura, hoy. Días después de que la síndico Liliana Ripoll (luego apodada por la gente como Vieja Chiflada) anunciara que "Racing ha dejado de existir), los hinchas dejaron las cuerdas vocales y el llanto desparramados por todos los rincones de la cancha en el ruego de que el club no cerrara sus puertas. Era una cuestión de vida o muerte del club. Sí, sin exageraciones esa vez.</p>
          <p>Gustavo Costas, quien en ese entonces hacía dupla técnica con Humberto Maschio, salía a la cancha junto a jugadores como Teté Quiroz, Sergio Zanetti y el Coco Reinoso (entre otros) se derretían por dentro al ver esa multitud cantando por Racing. Gracias a los hinchas, a esa jornada de altísimo impacto emocional, el club no cerró sus puertas. Y nació el Día del Hincha de Racing. Algunos prefieren no celebrarlo porque no quieren evocar tanta angustia. Otros, la mayoría, sí lo hacen.</p>         
          <p>Uno de los que hizo una mención fue Víctor Blanco, presidente de Racing, a través de su cuenta de Twitter (@Vbrvictor). "Feliz día para todo el mundo Racing en este día tan especial. No pudieron ni podrán nunca. Racing existe y existirá de pro vida mientras exista un racinguista en el mundo. A disfrutar de este presente, a tener siempre presente: primero Racing".</p>
          <p>También llegó el saludo por video de Sebastián Beccacece. "Es un día especial para los hinchas de Racing. Memorable. Salieron a autoconvocarse por su causa, por lo que quieren, lo que aman, lo que defienden.... Les mando un saludo muy grande y les agradezco, por este corto plazo, por el afecto y el trato recibido. Les mando un abrazo de corazón y les transmito que en sus referentes, Diego (Milito), Licha (López) e Iván (Pillud) tienen hombres que definen lo que es el perfil de una institución muy humilde, muy dispuesta y grande de corazón. Estamos encantados con eso", dijo en un video que le grabó el club.</p>
          <p>Claudio Ubeda, referente de la institución y coordinador de las Infantiles, dijo lo suyo en Twitter (@cfu06). "Feliz día para todos los que amamos esta hermosa camiseta", escribió en la red social. Cada 7 de marzo, siempre, el hincha de Racing se siente el más fiel del mundo por un club. Y está en todo su derecho.</p>
    </main>
  </div>    
</template>
