<template>
  <div class="new7">
    <img alt="super" src="../assets/mercado.jpg">
    <main class="container">
      <h2>Tinelli presidente</h2>
        <h4>Con el fin de la Superliga, en AFA se viene la Liga Profesional y Tapia ya les avisó a los dirigentes que el cargo más importante será para Marcelo, actual pope de San Lorenzo.</h4>
          <p>La Superliga ya es historia. Si bien seguirá en funcionamiento hasta el final de la temporada (termina el 31 de mayo), la AFA ya dio su veredicto y decidió terminar con el contrato. Este martes, minutos después de que Mariano Elizondo presentara su renuncia como presidente, los dirigentes de los clubes de Primera División comunicaron esa decisión en Puerto Madero y la ruptura será refrendada el martes que viene en Asamblea. Ahora se viene la Liga Profesional, con base en la calle Viamonte. Ante eso, Claudio Tapia, ya tiene decidido cómo estará conformada la estructura dirigencial en esta nueva etapa del fútbol argentino: Marcelo Tinelli es su candidato para la presidencia y Chiqui ya se le comunicó a los demás dirigentes.</p>
          <p>Desde que se decidió desarmar la Superliga, el nombre de Tinelli fue el que sonó más fuerte para hacerse cargo de la Liga Profesional. En esa primera reunión (la famosa cena de Carnaval en la casa de Tapia en la que no estuvo River), el armado quedó con Boca como vicepresidente primero y San Lorenzo como vicepresidente segundo, que luego podría subir a ocupar el cargo mayor. La tercera vicepresidencia sería para el Ascenso. Claro, el Millo, con Rodolfo D'Onofrio a la cabeza, se hizo sentir y al día siguiente hubo reunión con Tapia: el club de Núñez busca ser parte de las decisiones importantes.</p>
          <p>Poco después de la reunión entre Tapia y D'Onofrio, el mismo Chiqui recibió (y se fotografió) junto a Tinelli y Mario Pergolini (Boca), en un encuentro que tuvo que ver con el manejo de los derechos audiovisuales y las negociaciones por los derechos internacionales de la Primera División. Otro indicio del lugar que fue ganándose el nacido en Bolívar.</p> 
          <p>Si bien es cierto que el Cabezón picó en punta para presidir la Liga Profesional, también se manejaron otros nombres, como el de Nicolás Russo (presidente de Lanús) y Cristian Malaspina (presidente de Argentinos). Otro que sonó es el de Eduardo Spinosa, que no es dirigente de Banfield, pero tiene peso en AFA y podría tener un cargo secundario (CEO, por ejemplo).</p>
          <p>La novedad del día tiene que ver con que el Comité Ejecutivo de la AFA pasará de tener tres a seis vicepresidentes, según lo aseguró Nicolás Russo luego del encuentro de este martes a la mañana. Así se abre un lugar para River, quien reclamó su lugar pero no estuvo en la reunión. "Vamos a dejar plasmado el nuevo Comité Ejecutivo del cual va a haber una ampliación: de tres vicepresidentes vamos a pasar a seis, cuatro de Primer División, uno del ascenso metropolitano y uno del interior. También van a subir la cantidad de vocalías", declaró el dirigente del Grana. También habrá un Secretario General, un Tesorero y, por lógica, un representante de cada club de Primera. Víctor Blanco y Hugo Moyano también buscarán un lugar importante.</p>         
          <p>Claro, todos los cargos estarán por debajo de un presidente con súper poderes: Tapia. Todas las decisiones deberán ser refrendadas por AFA y por el Comité Ejecutivo.</p>
    </main>
  </div>    
</template>
